### PR TITLE
Add Urdu translations

### PR DESCRIPTION
**Pull request by yethrosh**
Urdu translations completed, please add them in application.

### CODE REVIEW

**Comment by Last-Order** [comment]
Thanks for your contribution, but please don't delete English language file.

**Comment by yethrosh** [comment]
Thanks for reply, I provided the translations and requested only to add them.

**Comment by Last-Order** [comment]
Yeah I know. But you deleted en-us.json in your pull request. Please update your pull request.
So if you weren't  familiar with Git, I would be happy to assist you to do this.

**Comment by yethrosh** [comment]
Oh, I am not familiar with git. How to update pull request?

**Comment by Last-Order** [comment]
Oh I see. So I will do that myself. Thanks for your contribution again!

**Comment by yethrosh** [comment]
Thanks. :)
There is a string in english "Edit via Wikiplus" which appears in edit summary. How to translate it?

**Pull request merged**
